const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const COURSE='CRS-05092026-1234';
const disabled={mode:'disabled',peserta:null,penceramah:null,revision:1};
const award=(noCpd='DVSCPD-2026-123',points=4)=>({noCpd,points});
const managed=(extra={})=>({mode:'managed',peserta:award(),penceramah:null,revision:3,...extra});
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
function harness(){
  const nodes={},calls=[];const storage={getItem:()=>null,setItem(){},removeItem(){}};
  const document={body:{appendChild(){}},querySelectorAll:()=>[],createElement:()=>({remove(){}}),getElementById:id=>nodes[id]||null};
  nodes.lo={style:{}};nodes.kuc={innerHTML:''};nodes.mka={innerHTML:''};nodes['mk-btn-save']={disabled:false};nodes.mk={remove(){nodes.removed=true}};
  const window={location:{pathname:'/spdk/',search:'',hash:'#admin-kursus',reload(){}},history:{replaceState(){}},addEventListener(){}};
  const context={console,document,window,navigator:{},localStorage:storage,sessionStorage:storage,URLSearchParams,AbortController,queueMicrotask,setTimeout,clearTimeout,confirm:()=>true,fetch:async()=>({ok:true,json:async()=>({})})};
  vm.createContext(context);vm.runInContext(script,context);vm.runInContext("S={token:'token',role:'admin',nama:'Admin'};authBootstrapDone=true",context);
  context.apiWithTimeout=async(action,payload)=>{calls.push({action,payload:JSON.parse(JSON.stringify(payload))});return{success:true}};
  function field(id,value=''){nodes[id]={value:String(value),checked:false,disabled:false,readOnly:false,style:{},focus(){this.focused=true}};return nodes[id];}
  for(const [id,value] of Object.entries({mkn:'Kursus',mkp:'Penerangan',mkm:'2026-09-05',mkt:'2026-09-06',mkmm:'08:00',mkmt:'17:00',mkl:'ITU',mkhp:'',mkrd:'',mktd:''}))field(id,value);
  function cpd({global=false,peserta=false,penceramah=false,pNo='',pPoints='',sNo='',sPoints=''}={}){
    field('mkcpd-on').checked=global;field('mkcpd-peserta-on').checked=peserta;field('mkcpd-penceramah-on').checked=penceramah;
    field('mkcpd-peserta-no',pNo);field('mkcpd-peserta-points',pPoints);field('mkcpd-penceramah-no',sNo);field('mkcpd-penceramah-points',sPoints);
  }
  function state(value){if(!context.kuCoursesGeneration)context.kuCoursesGeneration=1;context.kuCpdModal={index:null,courseId:'',generation:context.kuCoursesGeneration,revision:0,legacy:false,touched:true,busy:false,completed:false,closed:false,activeOperation:0,modal:nodes.mk,...value};}
  function replaceModal(value={}){
    const modal={removed:false,remove(){this.removed=true}};
    nodes.mk=modal;nodes.mka={innerHTML:''};nodes['mk-btn-save']={disabled:false};
    state({modal,...value});
    return{modal,state:context.kuCpdModal,error:nodes.mka,button:nodes['mk-btn-save']};
  }
  return{context,nodes,calls,cpd,state,field,replaceModal};
}
test('new course defaults to explicit disabled CPD without server metadata',async()=>{const h=harness();h.context.modalKursus();assert.equal(h.context.kuCpdModal.legacy,false);assert.match(h.context.kuCpdModal.modal.innerHTML,/mkcpd-on/);h.cpd();h.state({touched:false});await h.context.saveKursus();assert.deepEqual(h.calls[0].payload.cpdConfig,{mode:'disabled',peserta:null,penceramah:null});for(const key of ['revision','actor','role','updatedAt','updatedBy','Provider','Tahun'])assert.equal(key in h.calls[0].payload,false);});
test('new managed course survives a completed course-list refresh',async()=>{const h=harness();h.context.kuCoursesGeneration=5;h.context.modalKursus();const opened=h.context.kuCpdModal;h.cpd({global:true,peserta:true,pNo:'dvscpd-2026-777',pPoints:'2.75'});h.context.fetch=async()=>({json:async()=>({success:true,kursus:[]})});await h.context.loadKursus();assert.equal(h.context.kuCoursesGeneration,6);assert.equal(h.context.kuCpdModal,opened);await h.context.saveKursus();assert.equal(h.calls.length,1);assert.equal(h.calls[0].action,'ciptaKursus');assert.deepEqual(h.calls[0].payload.cpdConfig,{mode:'managed',peserta:award('DVSCPD-2026-777',2.75),penceramah:null});});
test('new disabled course survives a completed course-list refresh',async()=>{const h=harness();h.context.kuCoursesGeneration=8;h.context.modalKursus();h.cpd();h.context.fetch=async()=>({json:async()=>({success:true,kursus:[]})});await h.context.loadKursus();await h.context.saveKursus();assert.equal(h.calls.length,1);assert.equal(h.calls[0].action,'ciptaKursus');assert.deepEqual(h.calls[0].payload.cpdConfig,{mode:'disabled',peserta:null,penceramah:null});});
for(const scenario of [
  {name:'participant only',input:{global:true,peserta:true,pNo:'dvscpd-2026-123',pPoints:'2.5'},expected:{mode:'managed',peserta:award('DVSCPD-2026-123',2.5),penceramah:null}},
  {name:'speaker only',input:{global:true,penceramah:true,sNo:'vetcpd-2026-456',sPoints:'3'},expected:{mode:'managed',peserta:null,penceramah:award('VETCPD-2026-456',3)}},
  {name:'both categories',input:{global:true,peserta:true,penceramah:true,pNo:'dvscpd-2026-123',pPoints:'1.25',sNo:'vetcpd-2026-456',sPoints:'2.75'},expected:{mode:'managed',peserta:award('DVSCPD-2026-123',1.25),penceramah:award('VETCPD-2026-456',2.75)}}
])test('create sends '+scenario.name,async()=>{const h=harness();h.cpd(scenario.input);h.state();await h.context.saveKursus();assert.deepEqual(h.calls[0].payload.cpdConfig,scenario.expected);});
for(const scenario of [
  {name:'no category',input:{global:true},message:/sekurang-kurangnya/},
  {name:'missing participant number',input:{global:true,peserta:true,pPoints:'2'},message:/No\. CPD Peserta wajib/},
  {name:'missing speaker points',input:{global:true,penceramah:true,sNo:'VETCPD-2026-456'},message:/Mata CPD Penceramah wajib/},
  {name:'malformed number',input:{global:true,peserta:true,pNo:'bad',pPoints:'2'},message:/Format No\. CPD/},
  {name:'zero points',input:{global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'0'},message:/melebihi 0/},
  {name:'negative points',input:{global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'-1'},message:/melebihi 0/}
])test('create blocks '+scenario.name,async()=>{const h=harness();h.cpd(scenario.input);h.state();await h.context.saveKursus();assert.equal(h.calls.length,0);assert.match(h.nodes.mka.innerHTML,scenario.message);});
test('legacy is rendered distinctly and ordinary edit preserves omission',async()=>{const h=harness();const course={courseId:COURSE,cpdConfig:{mode:'legacy',peserta:null,penceramah:null,revision:0}};assert.match(h.context.kuCpdFormHtml(course,false),/Sumber CPD sedia ada/);assert.doesNotMatch(h.context.kuCpdFormHtml(course,false),/mkcpd-on/);h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=1;h.state({index:0,courseId:COURSE,legacy:true,revision:0,touched:false});await h.context.saveKursus(0);assert.equal('cpdConfig'in h.calls[0].payload,false);assert.equal('expectedCpdRevision'in h.calls[0].payload,false);});
test('disabled and managed forms load exact state and lock only the number',()=>{const h=harness();assert.match(h.context.kuCpdFormHtml({cpdConfig:disabled},false),/CPD Kursus/);const out=h.context.kuCpdFormHtml({cpdConfig:managed(),cpdNumberLocked:{peserta:true}},false);assert.match(out,/DVSCPD-2026-123/);assert.match(out,/value="4"/);assert.match(out,/mkcpd-peserta-no[^>]+readonly/);assert.doesNotMatch(out,/mkcpd-peserta-points[^>]+readonly/);});
test('managed edit includes current expected revision and permits points changes',async()=>{const h=harness(),course={courseId:COURSE,cpdConfig:managed()};h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=2;h.state({index:0,courseId:COURSE,generation:2,revision:3});h.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'7.75'});await h.context.saveKursus(0);assert.equal(h.calls[0].action,'kemaskinikursus');assert.equal(h.calls[0].payload.expectedCpdRevision,3);assert.equal(h.calls[0].payload.cpdConfig.peserta.points,7.75);});
test('untouched disabled edit omits CPD and stale revision blocks submission',async()=>{const h=harness(),course={courseId:COURSE,cpdConfig:disabled};h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=4;h.state({index:0,courseId:COURSE,generation:4,revision:1,touched:false});h.cpd();await h.context.saveKursus(0);assert.equal('cpdConfig'in h.calls[0].payload,false);const h2=harness();h2.context.kuKursusRows=[course];h2.context.kuCoursesGeneration=5;h2.state({index:0,courseId:COURSE,generation:4,revision:1});await h2.context.saveKursus(0);assert.equal(h2.calls.length,0);assert.match(h2.nodes.mka.innerHTML,/telah berubah/);});
test('edit remains blocked after list generation or config revision changes',async()=>{const course={courseId:COURSE,cpdConfig:managed()};const generation=harness();generation.context.kuKursusRows=[course];generation.context.kuCoursesGeneration=11;generation.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'5'});generation.state({index:0,courseId:COURSE,generation:10,revision:3});await generation.context.saveKursus(0);assert.equal(generation.calls.length,0);const revision=harness();revision.context.kuKursusRows=[course];revision.context.kuCoursesGeneration=10;revision.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'5'});revision.state({index:0,courseId:COURSE,generation:10,revision:2});await revision.context.saveKursus(0);assert.equal(revision.calls.length,0);});
test('completed course uses narrow action and exact payload',async()=>{const h=harness(),course={courseId:COURSE,statusAsal:'tamat',cpdConfig:managed()};h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=6;h.state({index:0,courseId:COURSE,generation:6,revision:3,completed:true});h.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'8'});await h.context.saveTetapanCpd();assert.deepEqual(h.calls[0],{action:'updateCourseCpdConfig',payload:{courseId:COURSE,expectedCpdRevision:3,cpdConfig:{mode:'managed',peserta:award('DVSCPD-2026-123',8),penceramah:null}}});});
test('completed action is role/status guarded and modal contains no general course fields',()=>{const h=harness(),course={courseId:COURSE,namaKursus:'Selesai',statusAsal:'tamat',cpdConfig:managed()};h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=1;h.context.modalTetapanCpd(0);assert.equal(h.context.kuCpdModal.completed,true);assert.doesNotMatch(h.context.kuCpdFormHtml(course,true),/mkn|mkm|mkl|mkhp/);vm.runInContext("S.role='peserta'",h.context);h.context.kuCpdModal=null;h.context.modalTetapanCpd(0);assert.equal(h.context.kuCpdModal,null);course.statusAsal='dibatal';vm.runInContext("S.role='admin'",h.context);h.context.modalTetapanCpd(0);assert.equal(h.context.kuCpdModal,null);});
test('double submit is blocked and transport uncertainty is never retried',async()=>{const h=harness(),pending=deferred();h.cpd();h.state();h.context.apiWithTimeout=async(action,payload)=>{h.calls.push({action,payload});return pending.promise};const one=h.context.saveKursus(),two=h.context.saveKursus();assert.equal(h.calls.length,1);pending.resolve({success:true});await Promise.all([one,two]);const h2=harness();h2.cpd();h2.state();h2.context.apiWithTimeout=async()=>{throw new Error('RAW SECRET')};await h2.context.saveKursus();assert.match(h2.nodes.mka.innerHTML,/tidak dapat dipastikan/);assert.doesNotMatch(h2.nodes.mka.innerHTML,/RAW SECRET/);});
test('configuration conflict invalidates the active modal',async()=>{const h=harness();h.cpd();const active=h.replaceModal();h.context.apiWithTimeout=async()=>({success:false,code:'CPD_CONFIG_CONFLICT'});await h.context.saveKursus();assert.equal(active.state.generation,-1);assert.equal(active.button.disabled,true);assert.match(active.error.innerHTML,/telah berubah/);});
test('stale course success cannot remove or reload a replacement modal',async()=>{const h=harness(),pending=deferred();h.cpd();const a=h.replaceModal({courseId:'',revision:0});let reloads=0;h.context.loadKursus=()=>{reloads++};h.context.apiWithTimeout=async()=>pending.promise;const save=h.context.saveKursus();h.context.kuCloseCourseModal();const b=h.replaceModal({courseId:'',revision:7});b.error.innerHTML='B';b.button.disabled=false;pending.resolve({success:true});await save;assert.equal(b.modal.removed,false);assert.equal(b.error.innerHTML,'B');assert.equal(b.button.disabled,false);assert.equal(reloads,0);assert.equal(h.context.kuCpdModal,b.state);assert.equal(a.modal.removed,true);});
test('stale course failure cannot render into a replacement modal',async()=>{const h=harness(),pending=deferred();h.cpd();h.replaceModal();h.context.apiWithTimeout=async()=>pending.promise;const save=h.context.saveKursus();h.context.kuCloseCourseModal();const b=h.replaceModal({revision:4});b.error.innerHTML='B';pending.resolve({success:false,code:'CPD_CONFIG_INVALID',message:'A'});await save;assert.equal(b.modal.removed,false);assert.equal(b.error.innerHTML,'B');assert.equal(h.context.kuCpdModal,b.state);});
test('old-session course success cannot mutate replacement-session UI',async()=>{const h=harness(),pending=deferred();h.cpd();const active=h.replaceModal();h.context.apiWithTimeout=async()=>pending.promise;const save=h.context.saveKursus();active.error.innerHTML='SESSION-B';vm.runInContext("S={token:'replacement',role:'admin',nama:'Baharu'}",h.context);pending.resolve({success:true});await save;assert.equal(active.modal.removed,false);assert.equal(active.error.innerHTML,'SESSION-B');assert.equal(vm.runInContext('S.token',h.context),'replacement');});
test('old-token auth failure cannot alter replacement session or its modal',async()=>{const h=harness(),pending=deferred();h.cpd();const active=h.replaceModal();h.context.apiWithTimeout=async()=>pending.promise;const save=h.context.saveKursus();active.error.innerHTML='SESSION-B';vm.runInContext("S={token:'replacement',role:'admin',nama:'Baharu'}",h.context);pending.resolve({success:false,auth:false,code:'CPD_AUTH_REQUIRED',message:'OLD'});await save;assert.equal(vm.runInContext('S.token',h.context),'replacement');assert.equal(active.error.innerHTML,'SESSION-B');assert.equal(active.modal.removed,false);});
test('stale completed-course response cannot mutate another completed-course modal',async()=>{const h=harness(),pending=deferred(),a={courseId:COURSE,statusAsal:'tamat',cpdConfig:managed()},bCourse={courseId:'CRS-05092026-5678',statusAsal:'tamat',cpdConfig:managed({revision:8})};h.context.kuKursusRows=[a,bCourse];h.context.kuCoursesGeneration=3;h.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'5'});h.replaceModal({index:0,courseId:a.courseId,generation:3,revision:3,completed:true});h.context.apiWithTimeout=async()=>pending.promise;const save=h.context.saveTetapanCpd();h.context.kuCloseCourseModal();const b=h.replaceModal({index:1,courseId:bCourse.courseId,generation:3,revision:8,completed:true});b.error.innerHTML='B-REV-8';pending.resolve({success:false,code:'CPD_CONFIG_CONFLICT'});await save;assert.equal(b.error.innerHTML,'B-REV-8');assert.equal(b.button.disabled,false);assert.equal(b.modal.removed,false);assert.equal(h.context.kuCpdModal.revision,8);});
test('cross-course revisions and repeated reopen ignore every older response',async()=>{const h=harness(),a=deferred(),b=deferred(),responses=[a.promise,b.promise];h.cpd();h.context.apiWithTimeout=async()=>responses.shift();const first=h.replaceModal({courseId:'',revision:1});const saveA=h.context.saveKursus();h.context.kuCloseCourseModal();const second=h.replaceModal({courseId:'',revision:2});const saveB=h.context.saveKursus();h.context.kuCloseCourseModal();const newest=h.replaceModal({courseId:'',revision:3});newest.error.innerHTML='NEWEST';a.resolve({success:true});b.resolve({success:false,code:'CPD_CONFIG_CONFLICT'});await Promise.all([saveA,saveB]);assert.equal(first.modal.removed,true);assert.equal(second.modal.removed,true);assert.equal(newest.modal.removed,false);assert.equal(newest.error.innerHTML,'NEWEST');assert.equal(newest.button.disabled,false);assert.equal(h.context.kuCpdModal.revision,3);});
test('stale final cleanup cannot clear a newer pending operation',async()=>{const h=harness(),a=deferred(),b=deferred(),responses=[a.promise,b.promise];h.cpd();h.context.apiWithTimeout=async()=>responses.shift();h.replaceModal({revision:1});const saveA=h.context.saveKursus();h.context.kuCloseCourseModal();const newest=h.replaceModal({revision:2});const saveB=h.context.saveKursus();a.resolve({success:false,code:'CPD_CONFIG_INVALID'});await saveA;assert.equal(h.nodes.lo.style.display,'flex');assert.equal(newest.state.busy,true);assert.equal(newest.button.disabled,true);b.resolve({success:false,code:'CPD_CONFIG_INVALID'});await saveB;});
test('current-token auth expiry closes and invalidates an ordinary course modal',async()=>{const h=harness(),pending=deferred();h.cpd();const active=h.replaceModal();h.context.fetch=async()=>pending.promise;h.context.apiWithTimeout=(action,payload)=>h.context.api(action,payload);const save=h.context.saveKursus();pending.resolve({json:async()=>({success:false,auth:false,code:'CPD_AUTH_REQUIRED'})});await save;assert.equal(active.modal.removed,true);assert.equal(active.state.closed,true);assert.equal(active.state.activeOperation,0);assert.equal(h.context.kuCpdModal,null);assert.equal(vm.runInContext('S.token',h.context),'');assert.equal(h.context.window.location.hash,'#login');});
test('current-token auth expiry closes a completed-course CPD modal',async()=>{const h=harness(),pending=deferred(),course={courseId:COURSE,statusAsal:'tamat',cpdConfig:managed()};h.context.kuKursusRows=[course];h.context.kuCoursesGeneration=2;h.cpd({global:true,peserta:true,pNo:'DVSCPD-2026-123',pPoints:'5'});const active=h.replaceModal({index:0,courseId:COURSE,generation:2,revision:3,completed:true});h.context.fetch=async()=>pending.promise;h.context.apiWithTimeout=(action,payload)=>h.context.api(action,payload);const save=h.context.saveTetapanCpd();pending.resolve({json:async()=>({success:false,auth:false})});await save;assert.equal(active.modal.removed,true);assert.equal(active.state.closed,true);assert.equal(h.context.kuCpdModal,null);assert.equal(vm.runInContext('S.token',h.context),'');assert.equal(h.context.window.location.hash,'#login');});
test('actual old-token auth failure preserves replacement session and modal',async()=>{const h=harness(),pending=deferred();h.cpd();h.replaceModal();h.context.fetch=async()=>pending.promise;h.context.apiWithTimeout=(action,payload)=>h.context.api(action,payload);const save=h.context.saveKursus();vm.runInContext("S={token:'replacement',role:'admin',nama:'Baharu'}",h.context);const replacement=h.replaceModal({revision:12});replacement.error.innerHTML='REPLACEMENT';pending.resolve({json:async()=>({success:false,auth:false})});await save;assert.equal(vm.runInContext('S.token',h.context),'replacement');assert.equal(replacement.modal.removed,false);assert.equal(replacement.error.innerHTML,'REPLACEMENT');assert.equal(h.context.window.location.hash,'#admin-kursus');});
test('current-token auth expiry is safe without a modal and after prior close',async()=>{for(const closeFirst of [false,true]){const h=harness();if(closeFirst){h.replaceModal();h.context.kuCloseCourseModal();}else h.context.kuCpdModal=null;h.context.fetch=async()=>({json:async()=>({success:false,auth:false})});await assert.rejects(()=>h.context.api('getSenaraiKursus'));assert.equal(vm.runInContext('S.token',h.context),'');assert.equal(h.context.kuCpdModal,null);assert.equal(h.context.window.location.hash,'#login');}});
test('response completion after auth cleanup cannot recreate or mutate the course modal',async()=>{const h=harness(),pending=deferred();h.cpd();const active=h.replaceModal();h.context.fetch=async()=>pending.promise;h.context.apiWithTimeout=(action,payload)=>h.context.api(action,payload);const save=h.context.saveKursus();pending.resolve({json:async()=>({success:false,auth:false})});await save;assert.equal(active.modal.removed,true);assert.equal(h.context.kuCpdModal,null);await Promise.resolve();assert.equal(h.context.kuCpdModal,null);assert.equal(vm.runInContext('S.token',h.context),'');});
test('all new backend errors map locally and raw messages are excluded',()=>{const h=harness();for(const code of ['CPD_CONFIG_INVALID','CPD_CONFIG_CONFLICT','CPD_CONFIG_NUMBER_LOCKED','CPD_MIXED_SOURCE_MODE','CPD_MANAGED_SOURCE_NOT_READY']){const value=h.context.kuCpdError({success:false,code,message:'RAW PRIVATE'});assert.ok(value);assert.doesNotMatch(value,/RAW PRIVATE/);}});
test('course save handler never renders a raw backend error',async()=>{const h=harness();h.cpd();h.replaceModal();h.context.apiWithTimeout=async()=>({success:false,code:'UNKNOWN',message:'RAW PRIVATE'});await h.context.saveKursus();assert.doesNotMatch(h.nodes.mka.innerHTML,/RAW PRIVATE/);assert.match(h.nodes.mka.innerHTML,/tidak dapat disahkan/);});
test('CPD form remains bounded, labelled, keyboard-native and touch sized',()=>{const h=harness(),out=h.context.kuCpdFormHtml({cpdConfig:managed()},false);assert.match(html,/\.course-cpd\{[^}]*max-width:100%[^}]*overflow:hidden/);assert.match(html,/\.course-cpd-grid\{[^}]*minmax\(190px,1fr\)/);assert.match(out,/for="mkcpd-on"/);assert.match(out,/for="mkcpd-peserta-no"/);assert.match(html,/\.course-cpd-check input\{[^}]*width:20px[^}]*height:20px/);});
